#include <string>
#include <unordered_map>
#include <algorithm>

/**
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 */
char findTheDifference(std::string s, std::string t) {
    std::unordered_map<char, int> chars;

    for (char ch : t)
        chars[ch]++;

    for (char ch : s)
        chars[ch]--;

    return std::find_if(chars.cbegin(), chars.cend(), [](auto entry) {
        return entry.second > 0;
    })->first;
}

int main() {
    
}